version: '3.1'

services:

  db:
    image: 'mysql:latest'
    restart: always
    container_name: 'mysql'
    command: --init-file /data/application/init.sql
    volumes:
      - ./db_data:/var/lib/mysql:rw
      - ./scripts/database.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: secret
    ports:
      - '3306:3306'

volumes:
  db_data:
